name: ci-cd
on:
  #push:
    #branches: ["main"]
  workflow_dispatch:
  
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4.1.5
      - name: docker hub auth
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker build and push
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            <>:v${{ github.run_number }}
            <>:latest
  cd:
    runs-on: ubuntu-latest
    needs: [ci]
    steps:
      - name: code checkout
        uses: actions/checkout@v4.1.5
      - name: k8s context config
        uses: azure/k8s-set-context@v4.0.0
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.K8S_CONFIG }}
      - name: manifest execution
        uses: azure/k8s-deploy@v5
        with:
          manifests: |
            ./k8s/deployment.yaml
          images: |
            <>

